version: '2.0'
services:
  angular-app:
    container_name: angular-app
    image: jassi1203/angular-app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
